/* TERYAQ Help Center: task-first, bilingual, and role-aware. */
(()=>{
'use strict';
const sections=[
  {id:'start',en:'Start here',ar:'ابدأ هنا'},
  {id:'create',en:'Create',ar:'الإنشاء'},
  {id:'submit',en:'Submit',ar:'التسليم'},
  {id:'review',en:'Review',ar:'المراجعة'},
  {id:'recovery',en:'Recovery',ar:'الاستعادة'},
  {id:'admin',en:'Admin',ar:'الإدارة',admin:true}
];
const topics=[
  {id:'first-steps',section:'start',title:['First use and account name','البدء واسم الحساب'],summary:['Sign in, complete your profile, and prepare the device.','سجّل الدخول وأكمل البروفايل وجهّز الجهاز.'],steps:[['Open the app online and sign in with your approved account.','Set your account name in Profile before creating or importing a document.','Choose a template from Templates, or open an assigned task in Course Progress.'],['افتح التطبيق مع الإنترنت وسجّل دخولك بالحساب المعتمد.','احفظ اسم الحساب في Profile قبل إنشاء مستند أو استيراده.','اختر قالبًا من Templates، أو افتح مهمة مكلّفًا بها في Course Progress.']]},
  {id:'offline',section:'start',title:['Work offline','العمل دون إنترنت'],summary:['What stays on this device and when it reaches the cloud.','ما الذي يُحفظ على الجهاز ومتى يصل للسحابة.'],steps:[['Sign in and complete a sync online on each device first.','Use the installed app or the same browser when offline; choose Continue Offline if prompted.','Edits remain on this device until the connection returns and sync succeeds.'],['سجّل الدخول وأكمل مزامنة ناجحة على كل جهاز أولًا.','افتح التطبيق المثبت أو المتصفح نفسه عند انقطاع الإنترنت، واختر Continue Offline إن ظهر.','تبقى التعديلات على الجهاز حتى يعود الاتصال وتنجح المزامنة.']],note:['Do not clear browser data while work is waiting to sync.','لا تمسح بيانات المتصفح إذا كان هناك عمل ينتظر المزامنة.']},
  {id:'scientific-draft',section:'create',title:['Create a scientific draft','إنشاء مسودة علمية'],summary:['Choose a text or figures template and complete its chapter information.','اختر قالب النص أو الصور وأكمل معلومات الشابتر.'],steps:[['Open Templates and choose Scientific Draft Text or Figures Guide Draft.','Select category, course, chapter, author, and version in the information card.','Create the document, then use the editor tabs and Save.'],['افتح Templates واختر قالب المسودة العلمية النصية أو قالب الصور.','حدّد التصنيف والمساق والشابتر والكاتب والنسخة في بطاقة المعلومات.','أنشئ الملف، ثم استخدم تبويبات المحرر وزر Save.']]},
  {id:'document-actions',section:'create',title:['Documents and export','المستندات والتصدير'],summary:['Open, duplicate, export, and manage document versions.','افتح المستند أو انسخه أو صدّره وتابع نسخه.'],steps:[['Find the document in Documents and open it.','Use File → Export for the formats available to its template.','Confirm the scientific draft version before exporting; use History / Versions for previous states.'],['ابحث عن المستند في Documents وافتحه.','استخدم File ثم Export للصيغ المتاحة لهذا القالب.','تأكّد من نسخة المسودة العلمية قبل التصدير، واستخدم History / Versions للنسخ السابقة.']],note:['The .teryaq file is the editable JSON package; exported HTML and PDF are delivery formats.','ملف ‎.teryaq هو حزمة JSON قابلة للاستيراد؛ HTML وPDF صيغ للتسليم.']},
  {id:'text-editor',section:'create',title:['Text formatting, tables, and outline','تنسيق النص والجداول والأوتلاين'],summary:['Find formatting controls and copy the numbered outline.','اعرف مكان أدوات التنسيق ونسخ الأوتلاين المرقّم.'],steps:[['Use Styles for document styles and Text Formatting for direction, alignment, size, B, I, U, and lists.','Use Insert and Table for figures and editable tables; open View → Outline to navigate headings.','Press Copy Outline beside Document Outline to copy numbered H1 and nested H2 headings.'],['استخدم Styles للستايلات وText Formatting للاتجاه والمحاذاة والحجم وB وI وU والقوائم.','استخدم Insert وTable للصور والجداول، وافتح View ثم Outline للتنقل بين العناوين.','اضغط Copy Outline بجانب Document Outline لنسخ H1 المرقمة وH2 التابعة لها.']]},
  {id:'figures',section:'create',title:['Figures Guide Draft','قالب صور المسودة'],summary:['Manage figures and export the figures-only PDF.','أدر الصور وصدّر PDF للصور وأكوادها فقط.'],steps:[['Create a Figures Guide Draft with its category, chapter, and version.','Upload each figure and check its code, details, and upload progress.','Use File → Export → Figures only PDF when the review requires each figure with its code.'],['أنشئ قالب الصور مع التصنيف والشابتر والنسخة.','ارفع كل صورة وتحقق من كودها وبياناتها وتقدم الرفع.','استخدم File ثم Export ثم Figures only PDF عندما تحتاج المراجعة الصور مع أكوادها فقط.']]},
  {id:'shooting-script',section:'create',title:['Shooting Script & Teleprompter','سكريبت التصوير والتيليبرومبتر'],summary:['Prepare script cues, then read with a fixed reading region.','جهّز إشارات السكربت ثم اقرأ بمنطقة قراءة ثابتة.'],steps:[['Create a Shooting Script and choose its version.','Use Script Cues for Intro, Light Pause, figure/table references, presenter notes, and review notes.','Open Teleprompter to set speed, reading region, theme, and fullscreen; Space toggles play in fullscreen.'],['أنشئ سكريبت تصوير وحدد نسخته.','استخدم Script Cues للانترو والفاصل والإشارة إلى صورة أو جدول وملاحظات المقدم والمراجعة.','افتح Teleprompter لضبط السرعة ومنطقة القراءة والمظهر وملء الشاشة؛ Space يبدّل التشغيل في ملء الشاشة.']],note:['Cues marked as non-spoken stay out of the Teleprompter.','الإشارات غير المقروءة لا تظهر في التيليبرومبتر.']},
  {id:'submissions',section:'submit',title:['Submit a version','تسليم نسخة'],summary:['Choose a form, attach the requested outputs, and review the summary.','اختر نموذجًا وأرفق المخرجات وراجع الملخص.'],steps:[['Open Submission Forms and select the correct form.','Choose category, course, chapter, author, and version; later choices follow earlier selections.','Attach each required file. Upload begins on attachment; watch its size, progress, and speed.','Review all sections and the delivery summary, then submit.'],['افتح Submission Forms واختر النموذج الصحيح.','حدّد التصنيف والمساق والشابتر والكاتب والنسخة؛ الخيارات اللاحقة تتبع السابقة.','أرفق كل ملف مطلوب. يبدأ الرفع عند إرفاقه، وتظهر المساحة والتقدم والسرعة.','راجع الأقسام وملخص التسليم، ثم أرسل النموذج.']]},
  {id:'delivery-history',section:'submit',title:['My submission history','تاريخ تسليماتي'],summary:['Open a recent submission to see its full answers and files.','افتح تسليمًا سابقًا لرؤية إجاباته وملفاته.'],steps:[['Scroll below the forms in Submission Forms.','Select a submission summary to expand its details.','Check the version and the uploaded files in that record.'],['انزل أسفل النماذج في Submission Forms.','اضغط ملخص التسليم لعرض تفاصيله.','تحقق من النسخة والملفات المرفوعة في السجل.']]},
  {id:'course-progress',section:'review',title:['Course Progress and assigned tasks','تقدم المساق والمهام المكلّف بها'],summary:['Follow the chapter workflow and see what needs action.','تابع سير عمل الشابتر وما يحتاج إجراء.'],steps:[['Open Course Progress and select a course or chapter.','The summary shows progress across the course; open a task to see its owner, status, and next action.','The assigned account works in its linked document; task permissions follow the assignment.'],['افتح Course Progress واختر المساق أو الشابتر.','الملخص يوضح تقدم المساق؛ افتح المهمة لرؤية المسؤول والحالة والخطوة التالية.','صاحب الحساب المكلّف يعمل على الملف المرتبط؛ صلاحيات المهمة تتبع التكليف.']]},
  {id:'reviews',section:'review',title:['Review and notifications','المراجعة والإشعارات'],summary:['Inspect a review request and respond to it.','افتح طلب المراجعة وردّ عليه.'],steps:[['Open a review request from Course Progress or its notification.','Review the submitted state and leave a decision or a requested change with a note.','Click a notification to mark that item as read.'],['افتح طلب المراجعة من Course Progress أو من إشعاره.','راجع النسخة المرسلة ثم اعتمدها أو اطلب تعديلًا مع ملاحظة.','الضغط على الإشعار يعلّم ذلك الإشعار كمقروء.']]},
  {id:'sync',section:'recovery',title:['Sync status and conflicts','حالة المزامنة والتعارضات'],summary:['Understand pending, synced, and conflict states.','افهم حالات الانتظار والمزامنة والتعارض.'],steps:[['Synced means the cloud accepted the latest saved revision; pending or local-only remains on this device.','Press Sync Now if a change waits after the connection returns.','For a conflict, compare the local and cloud states before Keep local, Use server, or Save both.'],['Synced تعني قبول السحابة لآخر تعديل محفوظ؛ pending وlocal-only تعني أن العمل ما زال على الجهاز.','اضغط Sync Now إذا بقي تعديل منتظرًا بعد عودة الاتصال.','عند التعارض، قارن النسختين قبل اختيار Keep local أو Use server أو Save both.']],note:['If unsure, Save both preserves separate copies for review.','إذا لم تكن متأكدًا، يحفظ Save both النسختين للمراجعة.']},
  {id:'history',section:'recovery',title:['History and Cloud Versions','التاريخ والنسخ السحابية'],summary:['Recover local snapshots or inspect a previous cloud version.','استعد لقطة محلية أو راجع نسخة سحابية سابقة.'],steps:[['Open History / Versions inside the document for local snapshots.','Open Cloud versions & compare to inspect two synchronized cloud versions.','Check the target document and version before restoring or downloading.'],['افتح History / Versions داخل المستند للقطات المحلية.','افتح Cloud versions & compare لمراجعة نسختين متزامنتين.','تحقق من المستند ورقم النسخة قبل الاستعادة أو التنزيل.']]},
  {id:'trash-backup',section:'recovery',title:['Trash, backup, and device downloads','السلة والنسخ الاحتياطي والتنزيل'],summary:['Restore deleted documents and keep a separate workspace backup.','استعد الملفات المحذوفة واحتفظ بنسخة احتياطية منفصلة.'],steps:[['Use Trash to restore a deleted document within the retention period.','In Settings, export a Workspace Backup before changing devices.','Choose a download folder in Settings where the browser supports it; otherwise use the browser’s normal download location.'],['استخدم Trash لاستعادة ملف محذوف خلال مدة الاحتفاظ.','صدّر Workspace Backup من Settings قبل تغيير الجهاز.','اختر مجلد التنزيل من Settings إذا دعمه المتصفح؛ وإلا يستخدم التطبيق مكان التنزيل المعتاد.']]},
  {id:'admin-content',section:'admin',admin:true,title:['Content Setup and account tasks','إعداد المحتوى والحسابات'],summary:['Manage categories, courses, chapters, versions, authors, and task owners.','أدر التصنيفات والمساقات والشابترات والنسخ والكتّاب وأصحاب المهام.'],steps:[['In Admin → Content Setup, use separate tabs for Categories, Courses, Chapters, Versions, and Authors.','Assign task owners from actual account profiles in Course Progress.','Review account requests and role access in the Admin workspace.'],['في Admin ثم Content Setup استخدم تبويبات Categories وCourses وChapters وVersions وAuthors.','عيّن أصحاب المهام من الحسابات الفعلية في Course Progress.','راجع طلبات الحسابات والصلاحيات من مساحة Admin.']]},
  {id:'admin-forms',section:'admin',admin:true,title:['Edit and preview submission forms','تعديل نماذج التسليم ومعاينتها'],summary:['Change sections, required fields, and the header image without filling a test submission.','عدّل الأقسام والحقول الإجبارية وصورة الواجهة دون تعبئة تسليم تجريبي.'],steps:[['Open form editing in Admin and select the form.','Edit its sections and fields, including the required toggle and header image.','Use Preview to inspect its appearance without submitting data.'],['افتح تعديل النماذج في Admin واختر النموذج.','عدّل أقسامه وحقوله، بما فيها خيار إجباري وصورة الواجهة.','استخدم Preview لمعاينة الشكل دون إرسال بيانات.']]},
  {id:'admin-archive',section:'admin',admin:true,title:['Archive and backup locations','الأرشيف وأماكن النسخ الاحتياطي'],summary:['Find delivered files by chapter and track external backup copies.','اعثر على الملفات حسب الشابتر وتابع نسخها الاحتياطية الخارجية.'],steps:[['Browse Archive by classification, course, chapter, document type, and version.','Download a file or all delivery files as a ZIP.','Record Google Drive link, hard-disk details, and Telegram details in Backup Locations for each submission.'],['تصفح Archive حسب التصنيف والمساق والشابتر والنوع والنسخة.','نزّل ملفًا واحدًا أو كل ملفات التسليم في ZIP.','سجل رابط Google Drive وتفاصيل القرص الصلب وتيليجرام في Backup Locations لكل تسليم.']]}
];
const quick=[
  {id:'scientific-draft',en:'Create a scientific draft',ar:'إنشاء مسودة علمية'},
  {id:'submissions',en:'Submit a version',ar:'تسليم نسخة'},
  {id:'reviews',en:'Review my task',ar:'مراجعة مهمتي'},
  {id:'sync',en:'Fix a sync issue',ar:'حل مشكلة مزامنة'}
];
const ui={
 en:{kicker:'TERYAQ HELP CENTER',title:'How can we help?',intro:'Choose a task below, or search the guide.',placeholder:'Search documents, submissions, sync…',tasks:'Start with a task',browse:'Browse the guide',step:'STEP BY STEP',note:'Note',empty:'No topics match your search.',topics:'topics'},
 ar:{kicker:'مركز مساعدة ترياق',title:'كيف نقدر نساعدك؟',intro:'اختر مهمة من الأسفل أو ابحث في الدليل.',placeholder:'ابحث عن مستند أو تسليم أو مزامنة…',tasks:'ابدأ بمهمة',browse:'تصفح الدليل',step:'خطوة بخطوة',note:'ملاحظة',empty:'لا توجد نتائج مطابقة لبحثك.',topics:'مواضيع'}
};
const state={lang:'en',category:'start',selected:'first-steps',query:''};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const tr=pair=>pair[state.lang==='ar'?1:0];
const available=()=>topics.filter(topic=>!topic.admin||window.TeryaqPlatform?.isAdmin());
function render(){
 const root=$('guideRoot');if(!root)return;
 const words=ui[state.lang];root.lang=state.lang;root.dir=state.lang==='ar'?'rtl':'ltr';
 $('guideKicker').textContent=words.kicker;$('guideTitle').textContent=words.title;$('guideIntro').textContent=words.intro;$('guideTaskHeading').textContent=words.tasks;$('guideBrowseHeading').textContent=words.browse;$('guideSearch').placeholder=words.placeholder;$('guideEmpty').textContent=words.empty;
 root.querySelectorAll('[data-guide-lang]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.guideLang===state.lang)));
 $('guideSections').innerHTML=sections.filter(section=>!section.admin||window.TeryaqPlatform?.isAdmin()).map(section=>`<button type="button" data-guide-category="${section.id}" aria-current="${section.id===state.category&&!state.query?'page':'false'}">${esc(section[state.lang])}</button>`).join('');
 $('guideQuickTasks').innerHTML=quick.map(item=>`<button type="button" data-guide-task="${item.id}" aria-pressed="${item.id===state.selected}"><span class="guide-quick-icon" aria-hidden="true">${item.id==='sync'?'↻':item.id==='submissions'?'↑':item.id==='reviews'?'✓':'+'}</span>${esc(item[state.lang])}</button>`).join('');
 const selected=available().find(topic=>topic.id===state.selected)||available()[0];
 $('guideFeature').innerHTML=`<span class="guide-step-label">${esc(words.step)}</span><h4>${esc(tr(selected.title))}</h4><p>${esc(tr(selected.summary))}</p><ol>${selected.steps[state.lang==='ar'?1:0].map(step=>`<li>${esc(step)}</li>`).join('')}</ol>${selected.note?`<div class="guide-feature-note"><b>${esc(words.note)}:</b> ${esc(tr(selected.note))}</div>`:''}`;
 const query=state.query.trim().toLocaleLowerCase();const matches=available().filter(topic=>query?Object.values(topic).join(' ').toLocaleLowerCase().includes(query):topic.section===state.category);
 $('guideResultCount').textContent=`${matches.length} ${words.topics}`;$('guideLibrary').innerHTML=matches.map(topic=>`<button type="button" class="guide-topic-row${topic.id===state.selected?' active':''}" data-guide-topic="${topic.id}"><span><b>${esc(tr(topic.title))}</b><small>${esc(tr(topic.summary))}</small></span><span aria-hidden="true">${state.lang==='ar'?'←':'→'}</span></button>`).join('');
 $('guideEmpty').classList.toggle('hidden',matches.length>0);
}
function bind(){const root=$('guideRoot');if(!root||root.dataset.bound)return;root.dataset.bound='true';
 root.addEventListener('click',event=>{
  const language=event.target.closest('[data-guide-lang]');if(language){state.lang=language.dataset.guideLang;render();return}
  const category=event.target.closest('[data-guide-category]');if(category){state.category=category.dataset.guideCategory;state.selected=available().find(topic=>topic.section===state.category)?.id||state.selected;state.query='';$('guideSearch').value='';render();$('guideFeature').scrollIntoView({behavior:'smooth',block:'nearest'});return}
  const topic=event.target.closest('[data-guide-topic],[data-guide-task]');if(topic){state.selected=topic.dataset.guideTopic||topic.dataset.guideTask;state.category=available().find(item=>item.id===state.selected)?.section||state.category;if(topic.dataset.guideTask){state.query='';$('guideSearch').value=''}render();$('guideFeature').scrollIntoView({behavior:'smooth',block:'nearest'});return}
 });
 $('guideSearch').addEventListener('input',event=>{state.query=event.target.value;render()});
}
window.TeryaqGuide={render(){bind();render()}};
})();
