/* TERYAQ Chapter Work Areas v2.8.6 — chapter-first workflow + scientific automation. */
(()=>{'use strict';
const api=()=>window.TeryaqPlatform,$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)],esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=value=>{const parts=String(value??'').trim().split(/\s+/).filter(Boolean);if(!parts.length)return '—';return parts.length===1?parts[0].slice(0,2).toUpperCase():(parts[0][0]+parts[parts.length-1][0]).toUpperCase()};
const areaDefs=[
 {key:'scientific',label:'Scientific Draft & Design',stage:'Scientific Draft'},
 {key:'script',label:'Script & Presenting',stage:'Shooting Script'},
 {key:'questions',label:'Questions',stage:'Questions'},
 {key:'flashcards',label:'Flashcards',stage:'Flashcards'},
 {key:'shooting',label:'Shooting / Production',stage:'Shooting'},
 {key:'montage',label:'Montage (Video Editing)',stage:'Editing'}
];
const roleLabels={course_lead:'Course Lead',scientific_lead:'Scientific Lead',script_lead:'Script Lead',ai_lead:'AI Lead'};
const stageRole=stage=>stage==='Scientific Draft'?'scientific_lead':stage==='Shooting Script'?'script_lead':['Questions','Flashcards'].includes(stage)?'ai_lead':null;
const statusLabel={approved:'Approved',in_review:'In review',in_progress:'In progress',changes_requested:'Changes requested',ready:'Ready',planned:'Planned',blocked:'Blocked'};
const statusHelp={
 planned:'Task is planned but is not ready to start yet.',ready:'All prerequisites are available and the task can begin.',in_progress:'Work on this task has started.',in_review:'The task was submitted and is awaiting review.',approved:'The task has been reviewed and approved.',changes_requested:'Changes were requested before approval.',blocked:'Work cannot continue until the blocking issue is resolved.'
};
const resourceDefs=[
 ['curriculum_outlines','Curriculum & Outlines'],['source_links','Source Links'],['timeline','Timeline'],['roles_distribution','Task & Role Distribution']
];
let host=null,options=null,workflows=[],tasks=[],roles=[],templates=[],executors=[],chapterRoles=[],course='',category='',chapter='',area='scientific',mode='chapters',people=[],directory=[],busy=false;
const u=()=>api().user(),isAdmin=()=>api().isAdmin(),byId=(arr,id)=>arr.find(x=>x.id===id),name=(arr,id,field='name')=>byId(arr||[],id)?.[field]||id||'—';
const courseRows=()=>options?.subjects?.filter(x=>x.active!==false&&(!category||x.category_id===category))||[];
const chapterRows=()=>options?.chapters?.filter(x=>x.subject_id===course&&x.active!==false)||[];
const currentWorkflow=id=>workflows.filter(w=>w.chapter_id===id).sort((a,b)=>b.cycle-a.cycle)[0];
const ofWorkflow=id=>tasks.filter(t=>t.workflow_id===id).sort((a,b)=>(a.sort_order||0)-(b.sort_order||0));
const roleForUser=(uid,c=course)=>roles.filter(r=>r.course_id===c&&r.user_id===uid).map(r=>r.role);
const isCourseLead=(c=course)=>isAdmin()||roles.some(r=>r.course_id===c&&r.user_id===u()?.id&&r.role==='course_lead');
const isCourseManager=(stage=null,c=course)=>isAdmin()||roles.some(r=>r.course_id===c&&r.user_id===u()?.id&&(r.role==='course_lead'||(!stage?true:r.role===stageRole(stage))));
const pct=items=>{const req=items.filter(t=>t.required);return req.length?Math.round(req.filter(t=>t.status==='approved').length/req.length*100):0};
const statusChip=s=>`<span class="workflow-state ${esc(s)}" title="${esc(statusHelp[s]||'')}">${esc(statusLabel[s]||s)}</span>`;
const areaItems=(list,a=area)=>list.filter(t=>t.stage===areaDefs.find(x=>x.key===a)?.stage);
const dateText=v=>v?new Date(v+'T00:00:00').toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';
const taskExecutors=id=>executors.filter(e=>e.task_id===id);
const taskExecutorNames=t=>t.assignment_mode==='course_team'?['Course Team']:taskExecutors(t.id).map(e=>name([...people,...directory],e.user_id,'display_name'));
const stateKey=()=>`teryaq:workflow-state:${u()?.id||'guest'}`;
function saveState(extra={}){try{localStorage.setItem(stateKey(),JSON.stringify({course,category,chapter,area,mode,scrollY:window.scrollY,...extra}))}catch{}}
function restoreState(){try{const s=JSON.parse(localStorage.getItem(stateKey())||'{}');if(s.category)category=s.category;if(s.course)course=s.course;if(s.chapter)chapter=s.chapter;if(s.area)area=s.area;if(s.mode)mode=s.mode;return s}catch{return{}}}
function restoreScroll(s){requestAnimationFrame(()=>window.scrollTo({top:Number(s?.scrollY||0)}))}
const avatarSources={};
function avatarMarkup(person,cls='avatar-mini'){const id=person?.id||person?.user_id||'',label=person?.display_name||person?.name||'User',src=avatarSources[id];return src?`<span class="${cls} avatar-photo-wrap"><img src="${esc(src)}" alt="${esc(label)}"></span>`:`<span class="${cls}">${esc(initials(label))}</span>`}
async function hydrateAvatars(rows=[]){await Promise.all((rows||[]).map(async p=>{const id=p?.id||p?.user_id,path=p?.avatar_path;if(!id||!path||avatarSources[id]!==undefined)return;avatarSources[id]='';try{avatarSources[id]=await api().workflowProfileAvatarSource(path)}catch{avatarSources[id]=''}}))}
function sanitizeRichHTML(html=''){const t=document.createElement('template');t.innerHTML=String(html);t.content.querySelectorAll('script,style,iframe,object,embed').forEach(n=>n.remove());t.content.querySelectorAll('*').forEach(el=>{[...el.attributes].forEach(a=>{if(a.name.startsWith('on')||(!['href','target','rel'].includes(a.name)&&a.name!=='class'))el.removeAttribute(a.name)});if(el.tagName==='A'){const href=el.getAttribute('href')||'';if(!/^https?:|^mailto:/i.test(href))el.removeAttribute('href');else{el.setAttribute('target','_blank');el.setAttribute('rel','noopener')}}});return t.innerHTML}
function richEditorMarkup(id,placeholder){return `<div class="workflow-rich-editor"><div class="workflow-rich-toolbar" data-rich-toolbar="${esc(id)}"><button type="button" data-cmd="bold"><b>B</b></button><button type="button" data-cmd="italic"><i>I</i></button><button type="button" data-cmd="underline"><u>U</u></button><button type="button" data-cmd="insertUnorderedList">• List</button><button type="button" data-cmd="insertOrderedList">1. List</button><button type="button" data-cmd="createLink">Link</button></div><div id="${esc(id)}" class="workflow-rich-input" contenteditable="true" data-placeholder="${esc(placeholder)}"></div></div>`}
function bindRichEditors(root){$$('[data-rich-toolbar]',root).forEach(tb=>{const editor=$('#'+CSS.escape(tb.dataset.richToolbar),root);$$('[data-cmd]',tb).forEach(btn=>btn.onclick=()=>{editor?.focus();const cmd=btn.dataset.cmd;if(cmd==='createLink'){const url=window.prompt('Paste link URL:');if(url)document.execCommand('createLink',false,url)}else document.execCommand(cmd,false,null)})})}
function openWorkflowModal({title,body,submitLabel='Save',wide=false,onSubmit}){document.querySelector('.workflow-modal-backdrop')?.remove();const wrap=document.createElement('div');wrap.className='workflow-modal-backdrop';wrap.innerHTML=`<section class="workflow-modal ${wide?'wide':''}" role="dialog" aria-modal="true"><header class="workflow-modal-head"><h3>${esc(title)}</h3><button class="workflow-modal-close" type="button" aria-label="Close">×</button></header><form class="workflow-modal-form"><div class="workflow-modal-body">${body}</div><footer class="workflow-modal-actions"><button class="btn" type="button" data-modal-cancel>Cancel</button><button class="btn primary" type="submit">${esc(submitLabel)}</button></footer></form></section>`;document.body.appendChild(wrap);const close=()=>wrap.remove();wrap.querySelector('.workflow-modal-close').onclick=close;wrap.querySelector('[data-modal-cancel]').onclick=close;wrap.onclick=e=>{if(e.target===wrap)close()};bindRichEditors(wrap);wrap.querySelector('form').onsubmit=async e=>{e.preventDefault();const btn=e.submitter||wrap.querySelector('button[type=submit]');btn.disabled=true;try{await onSubmit?.(wrap);if(document.body.contains(wrap))close()}catch(err){window.alert(err?.message||String(err))}finally{if(document.body.contains(btn))btn.disabled=false}};return wrap}
const scientificNumberMap={
  prepare:'1–4',scope:'1–4',sources:'1–4',timeline:'1–4',roles:'1–4',
  'draft-v1':'5',
  'first-report':'6.1','simplified-audit':'6.2',figures:'6.3','draft-v1-review':'6.1–6.3',
  'draft-v2':'7','draft-update-1':'7',
  'responsible-review':'8',
  'draft-v3':'9','draft-update-2':'9',
  'comprehensive-audit':'10','comprehensive-audit-1':'10',
  'draft-v4':'11','draft-update-3':'11',
  'design-draft':'12','design-v1':'12',
  'second-audit':'13.1','comprehensive-audit-2':'13.1',
  'author-review':'13.2','accuracy-review':'13.2',
  'draft-final':'14.1','design-v2':'14.1',
  'draft-v5':'14.2'
};
const scientificOrderMap={prepare:0,scope:0,'draft-v1':1,'first-report':2,'simplified-audit':3,figures:4,'draft-v1-review':2,'draft-v2':5,'draft-update-1':5,'responsible-review':6,'draft-v3':7,'draft-update-2':7,'comprehensive-audit':8,'comprehensive-audit-1':8,'draft-v4':9,'draft-update-3':9,'design-draft':10,'design-v1':10,'second-audit':11,'comprehensive-audit-2':11,'author-review':12,'accuracy-review':12,'draft-final':13,'design-v2':13,'draft-v5':14};
const scientificSort=(a,b)=>(scientificOrderMap[a.task_key]??999)-(scientificOrderMap[b.task_key]??999)||((a.sort_order||0)-(b.sort_order||0));
const taskNumber=t=>t?.stage==='Scientific Draft'?(scientificNumberMap[t.task_key]||t.display_number||t.sort_order):(t?.display_number||t?.sort_order||'—');
async function load(){
 options=await api().getContentOptions({force:true,strict:true});
 [workflows,tasks,roles,templates,executors,chapterRoles]=await Promise.all([
  api().workflowRows('course_workflows','select=id,course_id,chapter_id,cycle,created_at&order=created_at.desc'),
  api().workflowRows('workflow_tasks','select=id,workflow_id,task_key,title,description,stage,sort_order,display_number,depends_on,required,template_id,expected_version,author_id,owner_id,status,submitted_id,approved_id,blocked_reason,start_date,due_date,approved_at,approved_by,assignment_mode&order=sort_order.asc'),
  api().workflowRows('course_management_roles','select=course_id,user_id,role,permissions'),
  api().workflowRows('workflow_templates','select=id,title,steps,updated_at'),
  api().workflowRows('workflow_task_executors','select=task_id,user_id,assigned_at'),
  api().workflowRows('workflow_chapter_roles','select=workflow_id,role,user_id,assigned_at')
 ]);
 if(category&&!options.categories.some(x=>x.id===category))category='';
 if(!category)category=options.categories.find(x=>x.active!==false)?.id||'';
 if(course&&!options.subjects.some(x=>x.id===course))course='';
 if(!course||!courseRows().some(x=>x.id===course))course=courseRows()[0]?.id||'';
 people=course?await api().workflowRpc('workflow_people',{p_course:course}).catch(()=>[]):[];await hydrateAvatars(people);
}
async function render(target){host=target;const remembered=restoreState();host.innerHTML='<div class="submission-info">Loading course workspace…</div>';try{await load();paint();restoreScroll(remembered)}catch(error){host.innerHTML=`<div class="issue error">Course workspace unavailable: ${esc(error.message)}. Apply cloud migrations through 021, then reload.</div>`}}
function topNav(){const canReview=isAdmin()||roles.some(r=>r.course_id===course&&r.user_id===u()?.id);return `<nav class="workflow-view-tabs"><button data-mode="chapters" class="${mode==='chapters'?'active':''}">Chapters</button><button data-mode="team" class="${mode==='team'?'active':''}">Team & Task Executors</button><button data-mode="my" class="${mode==='my'?'active':''}">My Tasks</button>${canReview?`<button data-mode="reviews" class="${mode==='reviews'?'active':''}">Review Requests</button>`:''}</nav>`}
function paint(){if(!host)return;const rows=chapterRows();
 host.innerHTML=`<div class="workflow-page chapter-first-page"><div class="workflow-filter"><label>Category<select id="workflowCategory">${(options.categories||[]).filter(x=>x.active!==false).map(x=>`<option value="${esc(x.id)}" ${x.id===category?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label>Course<select id="workflowCourse">${courseRows().map(x=>`<option value="${esc(x.id)}" ${x.id===course?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>${isAdmin()?'<button class="btn" id="workflowManageTeam">Manage Course Roles</button>':''}</div>${topNav()}<div id="workflowContent">${mode==='chapters'?(chapter?chapterPage(chapter):chapterIndex(rows)):'<div class="submission-info">Loading…</div>'}</div></div>`;
 $('#workflowCategory',host).onchange=e=>{category=e.target.value;course='';chapter='';mode='chapters';saveState();void render(host)};$('#workflowCourse',host).onchange=e=>{course=e.target.value;chapter='';mode='chapters';saveState();void render(host)};$('#workflowManageTeam',host)?.addEventListener('click',()=>void manageRoles());$$('[data-mode]',host).forEach(b=>b.onclick=()=>{mode=b.dataset.mode;saveState();paint();void renderMode()});bind();void renderMode();
}
async function renderMode(){if(!host||mode==='chapters')return;const content=$('#workflowContent',host);if(mode==='team')return void renderTeamAssignments(content);if(mode==='my')return void renderMyTasks(content);if(mode==='reviews')return void renderReviewRequests(content)}
function chapterIndex(rows){return `<section class="chapter-index-head"><div><span class="eyebrow">COURSE</span><h2>${esc(name(options.subjects,course))}</h2><p>Select a chapter first. Every production area lives inside its chapter.</p></div></section><div class="workflow-chapter-grid">${rows.map(c=>{const w=currentWorkflow(c.id),list=w?ofWorkflow(w.id):[];return `<button class="page-form-card workflow-chapter-card" type="button" data-chapter="${esc(c.id)}"><span>Chapter ${esc(c.chapter_number)} ${w?`· Cycle ${w.cycle}`:''}</span><strong>${esc(c.title)}</strong><div class="workflow-meter"><i style="width:${pct(list)}%"></i></div><small>${w?`${pct(list)}% overall chapter progress`:'Not started'}</small></button>`}).join('')||'<div class="empty-state">No chapters in this course.</div>'}</div>`}
function chapterPage(id){const c=byId(chapterRows(),id),w=currentWorkflow(id);if(!c){chapter='';return chapterIndex(chapterRows())}const list=w?ofWorkflow(w.id):[],chapterPct=pct(list),author=w?chapterRoles.find(r=>r.workflow_id===w.id&&r.role==='scientific_author'):null;
 const nav=areaDefs.map(a=>{const ai=areaItems(list,a.key);return `<button class="chapter-area-tab ${area===a.key?'active':''}" data-area="${a.key}"><strong>${esc(a.label)}</strong><small>${ai.length?`${pct(ai)}%`:'0%'}</small></button>`}).join('');
 return `<div class="chapter-workspace"><div class="chapter-workspace-head"><button class="btn small" id="workflowBack">← Chapters</button><div><span class="eyebrow">${esc(name(options.subjects,course))}</span><h2>Chapter ${esc(c.chapter_number)} – ${esc(c.title)}</h2><p>${w?`Cycle ${w.cycle}`:'No workflow cycle yet'}</p></div><div class="chapter-progress-card"><small>Chapter Overall Progress</small><div class="workflow-meter"><i style="width:${chapterPct}%"></i></div><strong>${chapterPct}%</strong></div></div>${w?`<section class="chapter-role-strip"><div><small>Scientific Draft Author</small><strong>${author?esc(name([...people,...directory],author.user_id,'display_name')):'Not assigned'}</strong></div>${isCourseManager('Scientific Draft')?'<button class="btn small" id="assignScientificAuthor">Assign once for this chapter</button>':''}</section>`:''}<nav class="chapter-area-tabs">${nav}</nav>${w?areaPage(w,list):`<div class="empty-state">${isCourseManager()?'<button class="btn primary" id="workflowStart">Start chapter</button>':'This chapter has not been started yet.'}</div>`}</div>`}
function areaPage(w,list){const def=areaDefs.find(x=>x.key===area),rawItems=areaItems(list),items=area==='scientific'?rawItems.filter(t=>!['sources','timeline','roles'].includes(t.task_key)).sort(scientificSort):rawItems,done=rawItems.filter(t=>t.status==='approved'&&t.required).length,required=rawItems.filter(t=>t.required).length;
 return `<section class="area-hero"><div><span class="area-icon">${area==='scientific'?'▣':area==='script'?'▤':area==='questions'?'?':area==='flashcards'?'◇':area==='shooting'?'◉':'▸'}</span><div><h3>${esc(def.label)}</h3><p>${area==='scientific'?'المسودة العلمية والتصميم':area==='script'?'السكريبت والتقديم':'Chapter work area'}</p></div></div><div class="area-progress"><small>Workflow Progress</small><div class="workflow-meter"><i style="width:${pct(items)}%"></i></div><span>${done} of ${required} tasks completed</span></div></section>${area==='scientific'?`<div class="area-inline-tools"><button class="btn" id="preparationResources">Preparation & Rules</button></div>`:''}<div class="workflow-table-wrap"><table class="workflow-task-table"><thead><tr><th>#</th><th>Task</th><th>Description</th><th>Status</th><th>Task Executors</th><th>Start Date</th><th>Due Date</th><th>Actions</th></tr></thead><tbody>${items.map(t=>`<tr><td><span class="task-number">${esc(taskNumber(t))}</span></td><td><button class="task-link" data-task="${esc(t.id)}">${esc(['scope','prepare'].includes(t.task_key)&&area==='scientific'?'Preparation & Roles':t.title)}</button></td><td>${esc(['scope','prepare'].includes(t.task_key)&&area==='scientific'?'Tasks 1–4: curriculum, sources, timeline, and role distribution.':(t.description||'—'))}</td><td>${statusChip(t.status)}</td><td>${esc(taskExecutorNames(t).join(', ')||'Unassigned')}</td><td>${esc(dateText(t.start_date))}</td><td>${esc(dateText(t.due_date))}</td><td><button class="btn small" data-task="${esc(t.id)}">Open</button></td></tr>`).join('')||'<tr><td colspan="8"><div class="empty-state">No tasks in this work area yet.</div></td></tr>'}</tbody></table></div>`}
function bind(){$$('[data-chapter]',host).forEach(b=>b.onclick=()=>{chapter=b.dataset.chapter;area='scientific';mode='chapters';saveState();paint()});$$('[data-area]',host).forEach(b=>b.onclick=()=>{area=b.dataset.area;saveState();paint()});$$('[data-task]',host).forEach(b=>b.onclick=()=>{saveState({scrollY:window.scrollY});void taskDetail(b.dataset.task)});$('#workflowBack',host)?.addEventListener('click',()=>{chapter='';saveState();paint()});$('#workflowStart',host)?.addEventListener('click',()=>void createCycle());$('#preparationResources',host)?.addEventListener('click',()=>void preparationPage());$('#assignScientificAuthor',host)?.addEventListener('click',()=>void assignScientificAuthor())}
async function createCycle(){if(busy)return;busy=true;try{await api().workflowRpc('workflow_create',{p_course:course,p_chapter:chapter,p_new_cycle:false,p_reason:null});await load();paint()}catch(e){alert(e.message)}finally{busy=false}}
async function ensureDirectory(){if(!directory.length){directory=await api().workflowRpc('workflow_directory',{p_course:course}).catch(()=>[]);await hydrateAvatars(directory)}return directory}
async function manageRoles(){if(!isAdmin())return;await ensureDirectory();const content=$('#workflowContent',host),current=roles.filter(r=>r.course_id===course&&Object.keys(roleLabels).includes(r.role));content.innerHTML=`<div class="workflow-detail"><button class="btn small" id="teamBack">← Back</button><section class="page-form-card"><h3>Course Management Team</h3><p><b>Course Lead</b> oversees the whole course. Scientific, Script and AI Leads manage their specialized areas.</p><div id="courseRoleRows">${current.map(r=>`<div class="workflow-manage-row"><span><strong>${esc(name(directory,r.user_id,'display_name'))}</strong><small>${esc(roleLabels[r.role]||r.role)}</small></span><button class="btn small danger" data-remove-role="${esc(r.user_id)}|${esc(r.role)}">Remove</button></div>`).join('')||'<p class="hint">No course management roles assigned.</p>'}</div><div class="course-role-picker"><label>User<select id="roleUser"><option value="">Choose user…</option>${directory.map(p=>`<option value="${esc(p.id)}">${esc(p.display_name)}</option>`).join('')}</select></label><label>Role<select id="roleType">${Object.entries(roleLabels).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('')}</select></label><button class="btn primary" id="addRole">Assign role</button></div></section></div>`;$('#teamBack',content).onclick=()=>{mode='chapters';paint()};$('#addRole',content).onclick=()=>{const user=$('#roleUser',content).value,role=$('#roleType',content).value;if(user)void setRole(user,role,true)};$$('[data-remove-role]',content).forEach(b=>b.onclick=()=>{const [user,role]=b.dataset.removeRole.split('|');void setRole(user,role,false)})}
async function setRole(user,role,enabled){try{await api().workflowRpc('workflow_set_course_role',{p_course:course,p_user:user,p_role:role,p_enabled:enabled});await load();await manageRoles()}catch(e){alert(e.message)}}
async function assignScientificAuthor(){const w=currentWorkflow(chapter);if(!w)return;await ensureDirectory();openWorkflowModal({title:'Assign Scientific Draft Author',submitLabel:'Assign',body:`<label class="workflow-modal-field">Search user<input id="authorSearch" type="search" placeholder="Search by name"></label><div class="author-choice-list">${directory.map(p=>`<label data-author-row data-search="${esc((p.display_name||'').toLowerCase())}"><input type="radio" name="scientificAuthor" value="${esc(p.id)}">${avatarMarkup(p)}<span>${esc(p.display_name)}</span></label>`).join('')}</div>`,onSubmit:async root=>{const selected=root.querySelector('input[name="scientificAuthor"]:checked')?.value;if(!selected)throw new Error('Choose a user.');await api().workflowRpc('workflow_set_chapter_role',{p_workflow:w.id,p_role:'scientific_author',p_user:selected});await load();paint()}});const root=document.querySelector('.workflow-modal-backdrop'),search=$('#authorSearch',root);search.oninput=()=>{const q=search.value.trim().toLowerCase();$$('[data-author-row]',root).forEach(r=>r.hidden=!!q&&!r.dataset.search.includes(q))}}

async function preparationPage(){const w=currentWorkflow(chapter);if(!w)return;const content=$('#workflowContent',host);let resources=await api().workflowRows('workflow_chapter_resources',`workflow_id=eq.${encodeURIComponent(w.id)}&select=id,resource_key,label,kind,storage_path,url,value,created_at&order=created_at.asc`).catch(()=>[]);const canManage=isCourseManager('Scientific Draft');content.innerHTML=`<div class="workflow-detail preparation-v281"><button class="btn small" id="prepBack">← Back</button><section class="page-form-card"><div class="section-head-inline"><div><span class="eyebrow">SHARED RESOURCES</span><h3>Preparation & Rules</h3><p>Shared chapter resources visible to everyone in the course.</p></div></div><div class="preparation-resource-grid">${resourceDefs.map(([key,label])=>{const group=resources.filter(x=>x.resource_key===key);return `<article class="preparation-resource-card"><header><div><strong>${esc(label)}</strong><small>${group.length?`${group.length} item${group.length===1?'':'s'} added`:'Nothing added yet'}</small></div>${canManage?`<button class="btn small" data-edit-resource="${esc(key)}">+ Add</button>`:''}</header><div class="prep-resource-items">${group.length?group.map(r=>`<div class="prep-resource-item"><span class="resource-kind-icon">${r.kind==='image'?'▧':r.kind==='link'?'↗':r.kind==='text'?'T':'▤'}</span><div><strong>${esc(r.label||label)}</strong>${r.kind==='text'?`<div class="required-rich-text">${sanitizeRichHTML(r.value||'')}</div>`:`<small>${esc(r.kind==='link'?r.url:(r.storage_path||'File'))}</small>`}</div>${r.kind!=='text'?`<button class="btn small" data-open-resource="${esc(r.id)}">Open</button>`:''}${canManage?`<button class="icon-btn danger" data-delete-resource="${esc(r.id)}" title="Remove">×</button>`:''}</div>`).join(''):'<div class="task-empty-state compact"><strong>Missing</strong><span>Add text, links, files, or images.</span></div>'}</div></article>`}).join('')}</div></section></div>`;$('#prepBack',content).onclick=()=>paint();$$('[data-open-resource]',content).forEach(b=>b.onclick=()=>void openChapterResource(resources.find(r=>r.id===b.dataset.openResource)));$$('[data-edit-resource]',content).forEach(b=>b.onclick=()=>void editChapterResource(w,b.dataset.editResource,resourceDefs.find(x=>x[0]===b.dataset.editResource)?.[1]||b.dataset.editResource));$$('[data-delete-resource]',content).forEach(b=>b.onclick=()=>void deleteChapterResource(b.dataset.deleteResource))}
async function editChapterResource(w,key,label){openWorkflowModal({title:`Add ${label}`,wide:true,submitLabel:'Add Resources',body:`<p class="modal-helper">You can add any combination of text, links, files, and multiple images in one save.</p><div class="resource-type-grid"><section><h4>Text</h4>${richEditorMarkup('chapterResourceText',`Add ${label} notes or text…`)}</section><section><h4>Links</h4><textarea id="chapterResourceLinks" rows="4" placeholder="Paste one URL per line"></textarea></section><section><h4>Files</h4><label class="upload-dropzone">Choose one or more files<input id="chapterResourceFiles" type="file" multiple></label></section><section><h4>Images</h4><label class="upload-dropzone">Choose one or more images<input id="chapterResourceImages" type="file" accept="image/*" multiple></label></section></div>`,onSubmit:async root=>{const html=sanitizeRichHTML($('#chapterResourceText',root).innerHTML.trim()),links=$('#chapterResourceLinks',root).value.split(/\n+/).map(x=>x.trim()).filter(Boolean),files=[...$('#chapterResourceFiles',root).files],images=[...$('#chapterResourceImages',root).files];if(!html&&!links.length&&!files.length&&!images.length)throw new Error('Add at least one text, link, file, or image.');if(html)await api().workflowRpc('workflow_add_chapter_resource',{p_workflow:w.id,p_key:key,p_label:label,p_kind:'text',p_path:null,p_url:null,p_value:html});for(const url of links)await api().workflowRpc('workflow_add_chapter_resource',{p_workflow:w.id,p_key:key,p_label:label,p_kind:'link',p_path:null,p_url:url,p_value:null});await uploadWorkflowItems({files,kind:'file',w,label,key});await uploadWorkflowItems({files:images,kind:'image',w,label,key});await preparationPage()}})}
async function deleteChapterResource(id){if(!confirm('Remove this resource?'))return;try{await api().workflowRpc('workflow_delete_chapter_resource',{p_id:id});await preparationPage()}catch(e){alert(e.message)}}
async function openChapterResource(r){if(!r)return;if(r.kind==='link')return window.open(r.url,'_blank','noopener');if(r.kind==='text')return;try{const blob=await api().workflowResourceFile(r.storage_path);await api().downloadBlobToDevice(blob,(r.storage_path||'resource').split('/').pop())}catch(e){alert(e.message)}}
function statusFlow(t){const order=['planned','ready','in_progress','in_review','approved'],currentIndex=order.indexOf(t.status);return `<div class="task-progress-track arrow-flow">${order.map((st,i)=>{const cls=t.status===st?'current':currentIndex>i?'done':'future';return `<div class="task-progress-node ${cls}" data-status-tip="${esc(statusHelp[st])}" tabindex="0"><span></span><strong>${esc(statusLabel[st])}</strong><em class="status-tooltip">${esc(statusHelp[st])}</em></div>${i<order.length-1?'<b class="flow-arrow" aria-hidden="true">→</b>':''}`}).join('')}<div class="task-progress-special"><span class="flow-step changes_requested ${t.status==='changes_requested'?'current':''}" title="${esc(statusHelp.changes_requested)}">Changes requested</span><span class="flow-step blocked ${t.status==='blocked'?'current':''}" title="${esc(statusHelp.blocked)}">Blocked</span></div></div>`}
function taskActionButtons(t,isExecutor,canManage,submissionRequired){return `<div class="workflow-actions task-action-buttons">${isExecutor&&['ready','changes_requested'].includes(t.status)?'<button class="btn" data-action="start">Start task</button>':''}${isExecutor&&t.template_id==='scientific-draft-text'?'<button class="btn" id="workflowOpenEditor">Open editor</button>':''}${isExecutor&&submissionRequired?'<button class="btn primary" id="workflowSubmit">Submit Work</button>':''}${isExecutor&&!submissionRequired&&t.status==='in_progress'?'<button class="btn primary" data-action="request_review">Submit for review</button>':''}${canManage&&t.status==='in_review'?'<button class="btn primary" data-action="approve">Approve</button><button class="btn" data-action="changes">Request changes</button>':''}${canManage&&t.status==='blocked'?'<button class="btn" data-action="unblock">Unblock</button>':''}${canManage&&['ready','in_progress','changes_requested'].includes(t.status)?'<button class="btn" data-action="block">Mark as blocked</button>':''}</div>`}
function assignmentMarkup(t,execs,editable=true){const names=t.assignment_mode==='course_team'?['Course Team']:execs.map(x=>x.name);if(!editable)return `<section class="page-form-card task-card assignment-card"><div class="task-card-title"><span>👥</span><h4>Assignment & Schedule</h4></div><div class="assignment-readonly"><div><small>Task Executors</small><strong>${esc(names.join(', ')||'Unassigned')}</strong></div><div><small>Start Date</small><strong>${esc(dateText(t.start_date))}</strong></div><div><small>Due Date</small><strong>${esc(dateText(t.due_date))}</strong></div></div></section>`;
 return `<section class="page-form-card task-card assignment-card"><div class="task-card-title"><span>👥</span><h4>Assignment & Schedule</h4></div><div class="assignment-modern"><label class="course-team-toggle"><input type="checkbox" id="workflowCourseTeam" ${t.assignment_mode==='course_team'?'checked':''}> Assign to entire Course Team</label><div class="executor-select-wrap"><span class="field-label">Task Executors</span><div class="executor-selected" id="executorSelected">${execs.map(x=>`<span class="executor-pill"><b>${esc(initials(x.name))}</b>${esc(x.name)}</span>`).join('')||'<span class="hint">No executors selected</span>'}</div><details class="executor-dropdown" id="executorDropdown"><summary>${t.assignment_mode==='course_team'?'Course Team assigned':'Choose executors…'}</summary><div class="executor-dropdown-panel"><input type="search" id="executorSearch" placeholder="Search users…" autocomplete="off"><div class="executor-option-list">${directory.map(p=>`<label data-executor-row data-search="${esc((p.display_name||'').toLowerCase())}"><input type="checkbox" data-executor="${esc(p.id)}" ${execs.some(e=>e.id===p.id)?'checked':''} ${t.assignment_mode==='course_team'?'disabled':''}><span class="avatar-mini">${esc(initials(p.display_name))}</span><span>${esc(p.display_name)}</span></label>`).join('')}</div></div></details></div><div class="assignment-date-grid"><label>Start Date<input type="date" id="workflowStartDate" value="${esc(t.start_date||'')}"></label><label>Due Date<input type="date" id="workflowDueDate" value="${esc(t.due_date||'')}"></label></div><button class="btn primary assignment-save" id="workflowAssign">Save Assignment</button></div></section>`}
function requiredMarkup(required){const groups=(required||[]).filter(x=>x?.items),plain=(required||[]).filter(x=>!x?.items);return `${groups.map(g=>`<div class="required-input-group"><h5>${esc(g.group)} — ${esc(g.label)}</h5>${requiredRows(g.items)}</div>`).join('')}${plain.length?requiredRows(plain):''}`||'<div class="task-empty-state"><strong>No required inputs configured yet.</strong><span>Add files, links, text, or images needed for this task.</span></div>'}
function requiredRows(items){return `<div class="required-files-list modern">${(items||[]).map(i=>`<div class="required-file-row"><div class="required-file-main"><span class="resource-kind-icon">${i.kind==='image'?'▧':i.kind==='link'?'↗':i.kind==='text'?'T':'▤'}</span><div><strong>${esc(i.label)}</strong><small>${esc(i.source||'Required input')}</small>${i.kind==='text'&&i.value?`<div class="required-rich-text">${sanitizeRichHTML(i.value)}</div>`:''}</div></div><span class="required-file-status ${i.available?'available':i.required===false?'optional':'missing'}">${i.available?'Provided':i.required===false?'Optional':'Waiting'}</span>${i.available&&i.storage_path?`<button class="btn small" data-required-file="${esc(i.storage_path)}" data-required-bucket="${esc(i.source==='Added by course management'||i.source==='Preparation & Rules'?'workflow':'submission')}" data-filename="${esc(i.name||i.label)}">Open</button>`:i.available&&i.url?`<a class="btn small" href="${esc(i.url)}" target="_blank" rel="noopener">Open</a>`:''}</div>`).join('')}</div>`}
function assignmentFieldsMarkup(t,execs,editable=true){const names=t.assignment_mode==='course_team'?['Course Team']:execs.map(x=>x.name);if(!editable)return `<div class="task-info-assignment-readonly"><div><small>Task Executors</small><strong>${esc(names.join(', ')||'Unassigned')}</strong></div><div><small>Start Date</small><strong>${esc(dateText(t.start_date))}</strong></div><div><small>Due Date</small><strong>${esc(dateText(t.due_date))}</strong></div></div>`;
 return `<div class="task-info-assignment-edit"><label class="course-team-toggle"><input type="checkbox" id="workflowCourseTeam" ${t.assignment_mode==='course_team'?'checked':''}> Assign to entire Course Team</label><div class="executor-select-wrap"><span class="field-label">Task Executors</span><div class="executor-selected" id="executorSelected">${execs.map(x=>`<span class="executor-pill"><b>${esc(initials(x.name))}</b>${esc(x.name)}</span>`).join('')||'<span class="hint">No executors selected</span>'}</div><details class="executor-dropdown" id="executorDropdown"><summary>${t.assignment_mode==='course_team'?'Course Team assigned':'Choose executors…'}</summary><div class="executor-dropdown-panel"><input type="search" id="executorSearch" placeholder="Search users…" autocomplete="off"><div class="executor-option-list">${directory.map(p=>`<label data-executor-row data-search="${esc((p.display_name||'').toLowerCase())}"><input type="checkbox" data-executor="${esc(p.id)}" ${execs.some(e=>e.id===p.id)?'checked':''} ${t.assignment_mode==='course_team'?'disabled':''}><span class="avatar-mini">${esc(initials(p.display_name))}</span><span>${esc(p.display_name)}</span></label>`).join('')}</div></div></details></div><div class="assignment-date-grid"><label>Start Date<input type="date" id="workflowStartDate" value="${esc(t.start_date||'')}"></label><label>Due Date<input type="date" id="workflowDueDate" value="${esc(t.due_date||'')}"></label></div><button class="btn primary assignment-save" id="workflowAssign">Save Assignment</button></div>`}
function taskInformationMarkup(t,execs,canManage,areaLabel,ch,submissionRequired,history){const names=t.assignment_mode==='course_team'?'<span class="executor-pill compact">Course Team</span>':(execs.map(x=>`<span class="executor-pill compact">${avatarMarkup({id:x.id,name:x.name})}<span>${esc(x.name)}</span></span>`).join('')||'Unassigned');return `<section class="page-form-card task-card task-information-card"><div class="section-head-inline task-card-title"><div><span>▤</span><h4>Task Information</h4></div>${canManage?'<button class="btn small" id="editTaskInformation">✎ Edit</button>':''}</div><div class="task-info-rows"><div><small>Task ID</small><strong>${esc(t.task_key||t.id)}</strong></div><div><small>Work Area</small><strong>${esc(areaLabel)}</strong></div><div><small>Chapter</small><strong>${esc(ch?`${ch.chapter_number}. ${ch.title}`:'—')}</strong></div><div><small>Version</small><strong>${esc(t.expected_version||'—')}</strong></div><div><small>Description</small><strong>${esc(t.description||'—')}</strong></div><div><small>Task Executors</small><strong class="executor-inline-list">${names}</strong></div><div><small>Start Date</small><strong>${esc(dateText(t.start_date))}</strong></div><div><small>Due Date</small><strong>${esc(dateText(t.due_date))}</strong></div></div>${submissionRequired?`<div class="submission-required-card compact"><div><strong>Submission required</strong><span>${history.length?'Latest submission available':'No submission yet'}</span></div></div>`:''}${t.blocked_reason?`<p class="issue warn">Blocked: ${esc(t.blocked_reason)}</p>`:''}</section>`}
function activityMarkup(events){return `<section class="page-form-card task-card"><div class="task-card-title"><span>◷</span><h4>Activity</h4></div><div class="activity-timeline">${events.length?events.map(e=>`<div class="workflow-event"><i></i><div><strong>${esc(e.action)}</strong><time>${esc(new Date(e.created_at).toLocaleString())}</time><p>${esc(e.details?.note||'')}</p></div></div>`).join(''):'<p class="hint">No activity yet.</p>'}</div></section>`}
function instructionCards(collab,canManage,isExecutor){const state=collab.checkState||{},texts=(collab.instructions||[]).filter(i=>i.kind==='text'),checks=(collab.instructions||[]).filter(i=>i.kind==='checklist'),scopeBadge=i=>i.scope==='similar_tasks'?'<span class="instruction-scope">All similar tasks</span>':'<span class="instruction-scope local">This task</span>';return `<section class="page-form-card task-card"><div class="section-head-inline task-card-title"><div><span>▤</span><h4>Task Instructions</h4></div>${canManage?'<button class="btn small" id="addInstructionText">+ Add text</button>':''}</div>${texts.length?texts.map(i=>`<article class="task-instruction modern"><header><div><strong>${esc(i.title||'Instruction')}</strong>${scopeBadge(i)}</div>${canManage?`<button class="icon-btn" data-delete-instruction="${esc(i.id)}" title="Delete">×</button>`:''}</header><div class="instruction-rich">${sanitizeRichHTML(i.content?.html||esc(i.content?.text||''))}</div></article>`).join(''):'<div class="task-empty-state"><strong>No text instructions added.</strong><span>Add guidelines, notes, or directions for the executor.</span></div>'}</section><section class="page-form-card task-card"><div class="section-head-inline task-card-title"><div><span>☑</span><h4>Task Checklist</h4></div>${canManage?'<button class="btn small" id="addInstructionChecklist">+ Add checklist</button>':''}</div>${checks.length?checks.map(i=>`<article class="task-instruction modern"><header><div><strong>${esc(i.title||'Checklist')}</strong>${scopeBadge(i)}</div>${canManage?`<button class="icon-btn" data-delete-instruction="${esc(i.id)}" title="Delete">×</button>`:''}</header><div class="task-checklist">${(i.content?.items||[]).map(x=>`<label><input type="checkbox" data-instruction="${esc(i.id)}" data-check-item="${esc(x.id)}" ${state[`${i.id}:${x.id}`]?'checked':''} ${isExecutor?'':'disabled'}><span>${esc(x.label)}</span></label>`).join('')}</div></article>`).join(''):'<div class="task-empty-state"><strong>No checklist added yet.</strong><span>Create a step-by-step checklist for this task.</span></div>'}</section>`}
function commentsMarkup(collab,id){return `<section class="page-form-card task-card"><div class="task-card-title"><span>💬</span><h4>Comments (${(collab.comments||[]).length})</h4></div><div class="comment-compose modern"><textarea id="taskComment" rows="2" placeholder="Write a comment…"></textarea><button class="btn primary" id="postComment">Post</button></div><div class="task-comments modern">${(collab.comments||[]).map(c=>`<article><span class="avatar-mini">${esc(initials(c.author_name))}</span><div><header><strong>${esc(c.author_name)}</strong><time>${esc(new Date(c.created_at).toLocaleString())}</time></header><p>${esc(c.body)}</p></div></article>`).join('')||'<p class="hint">No comments yet.</p>'}</div></section>`}
async function taskDetail(id){const t=tasks.find(x=>x.id===id);if(!t)return;const w=workflows.find(x=>x.id===t.workflow_id),canManage=isCourseManager(t.stage,w.course_id),isExecutor=await api().workflowRpc('workflow_task_is_executor',{p_task:id,p_user:u()?.id}).catch(()=>false),content=$('#workflowContent',host);if(canManage)await ensureDirectory();const [collab,required,history,events]=await Promise.all([api().workflowRpc('workflow_task_collaboration',{p_task:id}).catch(()=>({executors:[],instructions:[],checkState:{},comments:[]})),api().workflowRpc('workflow_required_inputs',{p_task:id}).catch(()=>null),api().workflowRpc('workflow_task_submission_history',{p_task:id}).catch(()=>[]),api().workflowRows('workflow_events',`task_id=eq.${encodeURIComponent(id)}&select=id,action,details,created_at&order=created_at.desc&limit=30`).catch(()=>[])]);const execs=collab.executors||[],submissionRequired=!!t.template_id,ch=byId(options.chapters,w.chapter_id),areaLabel=areaDefs.find(a=>a.stage===t.stage)?.label||t.stage;
 content.innerHTML=`<div class="workflow-detail task-detail-v281 task-detail-v283"><div class="task-detail-toolbar"><button class="btn small" id="workflowDetailBack">← Back to Chapter</button><div class="task-breadcrumb">${esc(name(options.subjects,w.course_id))} › Chapter ${esc(ch?.chapter_number||'')} › ${esc(areaLabel)} › Task ${esc(taskNumber(t))}</div></div><section class="task-title-card"><div><small>${esc(areaLabel)} · Task ${esc(taskNumber(t))}</small><h2>${esc(t.title)}</h2><p>${esc(t.description||'')}</p></div>${statusChip(t.status)}</section><div class="task-top-grid">${taskInformationMarkup(t,execs,canManage,areaLabel,ch,submissionRequired,history)}<section class="page-form-card task-card status-progress-card"><div class="task-card-title"><span>◉</span><h4>Status & Progress</h4></div>${statusFlow(t)}${taskActionButtons(t,isExecutor,canManage,submissionRequired)}</section></div>${required!==null?`<section class="page-form-card task-card"><div class="section-head-inline task-card-title"><div><span>📎</span><h4>Required Files / Inputs</h4></div>${canManage?'<button class="btn small" id="addTaskResource">+ Add required input</button>':''}</div>${requiredMarkup(required)}</section>`:''}${history.length?`<section class="page-form-card task-card"><div class="task-card-title"><span>↺</span><h4>Submission History</h4></div>${history.map((s,i)=>`<details class="workflow-snapshot" ${i===0?'open':''}><summary><strong>${i===0?'Latest Submission':'Previous Submission'} · ${esc(s.version_label||'—')}</strong><time>${esc(new Date(s.submitted_at).toLocaleString())}</time></summary><div class="submitted-file-list">${(s.files||[]).map(f=>`<button class="btn small" data-submission-file="${esc(f.path)}" data-filename="${esc(f.name||f.label||'file')}">${esc(f.label||f.fieldId||f.name)}</button>`).join('')||'<span class="hint">No files</span>'}</div></details>`).join('')}</section>`:''}<div class="task-paired-grid instructions-checklist-grid">${instructionCards(collab,canManage,isExecutor)}</div><div class="task-paired-grid comments-activity-grid">${commentsMarkup(collab,id)}${activityMarkup(events)}</div></div>`;
 $('#workflowDetailBack',content).onclick=()=>{paint();restoreScroll(restoreState())};$$('[data-action]',content).forEach(b=>b.onclick=()=>void act(id,b.dataset.action));$('#workflowOpenEditor',content)?.addEventListener('click',()=>void window.TeryaqAppWorkflow?.openTask(t,w,options).catch(e=>alert(e.message)));$('#workflowSubmit',content)?.addEventListener('click',()=>void window.TeryaqSubmissions?.openForTask(t,w).catch(e=>alert(e.message)));$('#workflowAssign',content)?.addEventListener('click',()=>void saveAssignment(t,content));$('#editTaskInformation',content)?.addEventListener('click',()=>void editTaskInformation(t,execs));$('#addInstructionText',content)?.addEventListener('click',()=>void addInstruction(id,'text'));$('#addInstructionChecklist',content)?.addEventListener('click',()=>void addInstruction(id,'checklist'));$('#postComment',content)?.addEventListener('click',()=>void postComment(id,content));$('#addTaskResource',content)?.addEventListener('click',()=>void addTaskResource(t,w));$$('[data-delete-instruction]',content).forEach(b=>b.onclick=()=>void deleteInstruction(id,b.dataset.deleteInstruction));$$('[data-check-item]',content).forEach(c=>c.onchange=()=>void toggleCheck(id,c.dataset.instruction,c.dataset.checkItem,c.checked));$$('[data-submission-file]',content).forEach(b=>b.onclick=()=>void downloadSubmissionFile(b.dataset.submissionFile,b.dataset.filename));$$('[data-required-file]',content).forEach(b=>b.onclick=()=>void downloadRequiredFile(b.dataset.requiredFile,b.dataset.filename,b.dataset.requiredBucket));bindAssignmentPicker(content,t,execs)
}
function bindAssignmentPicker(content,t,execs){const team=$('#workflowCourseTeam',content),search=$('#executorSearch',content);if(!team)return;const refresh=()=>{const checked=$$('[data-executor]:checked',content),box=$('#executorSelected',content);if(box)box.innerHTML=checked.length?checked.map(x=>{const row=x.closest('[data-executor-row]'),n=row?.querySelector('span:last-child')?.textContent||'';return `<span class="executor-pill"><b>${esc(initials(n))}</b>${esc(n)}</span>`}).join(''):'<span class="hint">No executors selected</span>'};team.onchange=()=>{$$('[data-executor]',content).forEach(x=>x.disabled=team.checked);const d=$('#executorDropdown',content);if(d){d.classList.toggle('disabled',team.checked);if(team.checked)d.open=false}};$$('[data-executor]',content).forEach(x=>x.onchange=refresh);if(search)search.oninput=()=>{const q=search.value.trim().toLowerCase();$$('[data-executor-row]',content).forEach(r=>r.hidden=!!q&&!r.dataset.search.includes(q))}}
async function editTaskInformation(t,execs){await ensureDirectory();const w=workflows.find(x=>x.id===t.workflow_id);const modal=openWorkflowModal({title:'Edit Task Information',wide:true,submitLabel:'Save changes',body:`<label class="course-team-toggle"><input type="checkbox" id="workflowCourseTeam" ${t.assignment_mode==='course_team'?'checked':''}> Assign to entire Course Team</label><label class="workflow-modal-field">Task Executors<div class="executor-selected" id="executorSelected">${execs.map(x=>`<span class="executor-pill">${avatarMarkup({id:x.id,name:x.name})}<span>${esc(x.name)}</span></span>`).join('')||'<span class="hint">No executors selected</span>'}</div><input type="search" id="executorSearch" placeholder="Search users…"></label><div class="executor-option-list modal-executor-list">${directory.map(p=>`<label data-executor-row data-search="${esc((p.display_name||'').toLowerCase())}"><input type="checkbox" data-executor="${esc(p.id)}" ${execs.some(e=>e.id===p.id)?'checked':''} ${t.assignment_mode==='course_team'?'disabled':''}>${avatarMarkup(p)}<span>${esc(p.display_name)}</span></label>`).join('')}</div><div class="assignment-date-grid"><label>Start Date<input type="date" id="workflowStartDate" value="${esc(t.start_date||'')}"></label><label>Due Date<input type="date" id="workflowDueDate" value="${esc(t.due_date||'')}"></label></div>`,onSubmit:async root=>{const team=$('#workflowCourseTeam',root).checked,users=$$('[data-executor]:checked',root).map(x=>x.dataset.executor);await api().workflowRpc('workflow_set_task_executors',{p_task:t.id,p_users:users,p_course_team:team});await api().workflowRpc('workflow_update_schedule',{p_task:t.id,p_start:$('#workflowStartDate',root).value||null,p_due:$('#workflowDueDate',root).value||null});await load();await taskDetail(t.id)}});const team=$('#workflowCourseTeam',modal),search=$('#executorSearch',modal),refresh=()=>{const checked=$$('[data-executor]:checked',modal),box=$('#executorSelected',modal);box.innerHTML=checked.length?checked.map(x=>{const p=directory.find(p=>p.id===x.dataset.executor);return `<span class="executor-pill">${avatarMarkup(p)}<span>${esc(p?.display_name||'')}</span></span>`}).join(''):'<span class="hint">No executors selected</span>'};team.onchange=()=>{$$('[data-executor]',modal).forEach(x=>x.disabled=team.checked)};$$('[data-executor]',modal).forEach(x=>x.onchange=refresh);search.oninput=()=>{const q=search.value.trim().toLowerCase();$$('[data-executor-row]',modal).forEach(r=>r.hidden=!!q&&!r.dataset.search.includes(q))}}
async function saveAssignment(t,content){try{const team=$('#workflowCourseTeam',content).checked,users=$$('[data-executor]:checked',content).map(x=>x.dataset.executor);await api().workflowRpc('workflow_set_task_executors',{p_task:t.id,p_users:users,p_course_team:team});await api().workflowRpc('workflow_update_schedule',{p_task:t.id,p_start:$('#workflowStartDate',content).value||null,p_due:$('#workflowDueDate',content).value||null});await load();await taskDetail(t.id)}catch(e){alert(e.message)}}
async function uploadWorkflowItems({files,kind,w,t,label,key}){for(const file of files||[]){const safe=file.name.replace(/[^a-z0-9._-]+/gi,'_'),path=t?`${w.id}/tasks/${t.id}/${Date.now()}_${safe}`:`${w.id}/${key}/${Date.now()}_${safe}`;await api().uploadWorkflowResource(path,file);if(t)await api().workflowRpc('workflow_add_task_resource',{p_task:t.id,p_label:`${label}${files.length>1?` — ${file.name}`:''}`,p_kind:kind,p_path:path,p_url:null,p_value:null,p_required:true});else await api().workflowRpc('workflow_add_chapter_resource',{p_workflow:w.id,p_key:key,p_label:`${label}${files.length>1?` — ${file.name}`:''}`,p_kind:kind,p_path:path,p_url:null,p_value:null})}}
async function addTaskResource(t,w){const modal=openWorkflowModal({title:'Add Required Input',wide:true,submitLabel:'Add Input',body:`<label class="workflow-modal-field">Label<input id="resourceLabel" placeholder="e.g. Reference material"></label><div class="resource-type-grid"><section><h4>Text</h4>${richEditorMarkup('resourceText','Add notes or required text…')}</section><section><h4>Link</h4><textarea id="resourceLinks" rows="4" placeholder="Paste one URL per line"></textarea></section><section><h4>Files</h4><label class="upload-dropzone">Choose files<input id="resourceFiles" type="file" multiple></label></section><section><h4>Images</h4><label class="upload-dropzone">Choose images<input id="resourceImages" type="file" accept="image/*" multiple></label></section></div>`,onSubmit:async root=>{const label=$('#resourceLabel',root).value.trim()||'Required input',html=sanitizeRichHTML($('#resourceText',root).innerHTML.trim()),links=$('#resourceLinks',root).value.split(/\n+/).map(x=>x.trim()).filter(Boolean),files=[...$('#resourceFiles',root).files],images=[...$('#resourceImages',root).files];if(!html&&!links.length&&!files.length&&!images.length)throw new Error('Add at least one text, link, file, or image.');if(html)await api().workflowRpc('workflow_add_task_resource',{p_task:t.id,p_label:label,p_kind:'text',p_path:null,p_url:null,p_value:html,p_required:true});for(const url of links)await api().workflowRpc('workflow_add_task_resource',{p_task:t.id,p_label:links.length>1?`${label} — Link`:label,p_kind:'link',p_path:null,p_url:url,p_value:null,p_required:true});await uploadWorkflowItems({files,kind:'file',w,t,label});await uploadWorkflowItems({files:images,kind:'image',w,t,label});await taskDetail(t.id)}});return modal}
async function addInstruction(taskId,kind){const scope=`<fieldset class="instruction-scope-picker"><legend>Instruction Scope</legend><label><input type="radio" name="instructionScope" value="task" checked> This task only</label><label><input type="radio" name="instructionScope" value="similar_tasks"> All similar tasks across chapters</label><small>“Similar” means the same task key inside this course.</small></fieldset>`;if(kind==='text')return void openWorkflowModal({title:'Add Task Instruction',wide:true,submitLabel:'Add Instruction',body:`<label class="workflow-modal-field">Instruction title<input id="instructionTitle" placeholder="e.g. General notes"></label>${richEditorMarkup('instructionText','Write the task instruction…')}${scope}`,onSubmit:async root=>{const title=$('#instructionTitle',root).value.trim(),html=sanitizeRichHTML($('#instructionText',root).innerHTML.trim()),selected=root.querySelector('input[name="instructionScope"]:checked')?.value||'task';if(!html)throw new Error('Instruction text is required.');await api().workflowRpc('workflow_add_instruction',{p_task:taskId,p_kind:'text',p_title:title,p_content:{html},p_scope:selected});await taskDetail(taskId)}});
 openWorkflowModal({title:'Add Task Checklist',wide:true,submitLabel:'Add Checklist',body:`<label class="workflow-modal-field">Checklist title<input id="checklistTitle" placeholder="e.g. Simplified Audit Checklist"></label><div class="checklist-builder"><div id="checklistItems"></div><button type="button" class="btn small" id="addChecklistItem">+ Add item</button></div>${scope}`,onSubmit:async root=>{const title=$('#checklistTitle',root).value.trim(),labels=$$('[data-checklist-input]',root).map(x=>x.value.trim()).filter(Boolean),selected=root.querySelector('input[name="instructionScope"]:checked')?.value||'task';if(!labels.length)throw new Error('Add at least one checklist item.');const items=labels.map((label,i)=>({id:`item-${Date.now()}-${i}`,label}));await api().workflowRpc('workflow_add_instruction',{p_task:taskId,p_kind:'checklist',p_title:title,p_content:{items},p_scope:selected});await taskDetail(taskId)}});const root=document.querySelector('.workflow-modal-backdrop'),list=$('#checklistItems',root),add=()=>{const row=document.createElement('div');row.className='checklist-builder-row';row.innerHTML=`<span>⋮⋮</span><input data-checklist-input placeholder="Enter checklist item…"><button type="button" class="icon-btn" title="Remove">×</button>`;row.querySelector('button').onclick=()=>row.remove();list.appendChild(row)};$('#addChecklistItem',root).onclick=add;add();add();add()}
async function deleteInstruction(taskId,id){if(!confirm('Delete this instruction? Shared instructions will be removed from all matching tasks.'))return;await api().workflowRpc('workflow_delete_instruction',{p_id:id});await taskDetail(taskId)}
async function toggleCheck(taskId,instruction,item,checked){try{await api().workflowRpc('workflow_toggle_check',{p_instruction:instruction,p_item:item,p_checked:checked})}catch(e){alert(e.message);await taskDetail(taskId)}}
async function postComment(taskId,content){const body=$('#taskComment',content)?.value?.trim();if(!body)return;try{await api().workflowRpc('workflow_add_comment',{p_task:taskId,p_body:body});await taskDetail(taskId)}catch(e){alert(e.message)}}
async function downloadSubmissionFile(path,filename){try{const blob=await api().workflowFile(path);await api().downloadBlobToDevice(blob,filename||path.split('/').pop())}catch(e){alert(e.message)}}
async function downloadRequiredFile(path,filename,bucket){try{const blob=bucket==='workflow'?await api().workflowResourceFile(path):await api().workflowFile(path);await api().downloadBlobToDevice(blob,filename||path.split('/').pop())}catch(e){alert(e.message)}}
async function act(id,action){let note=null,documentId=null,task=tasks.find(t=>t.id===id);if(action==='changes'||action==='block'||(action==='request_review'&&!task?.template_id)){note=prompt(action==='changes'?'What needs to change?':action==='block'?'Reason for blocking this task:':'Describe the work completed for review:');if(!note?.trim())return}if(action==='request_review'&&task?.template_id){documentId=window.TeryaqAppWorkflow?.linkedDocumentId(id);if(task.template_id==='scientific-draft-text'&&!documentId)return alert('Open the assigned editor and sync its document before requesting review.')}try{await api().workflowRpc('workflow_action',{p_task:id,p_action:action,p_owner:null,p_reviewer:null,p_author:null,p_note:note,p_document_id:documentId});await load();await taskDetail(id);window.TeryaqAppWorkflow?.refreshNotifications()}catch(e){alert(e.message)}}

async function renderMyTasks(content){content.innerHTML='<div class="submission-info">Loading your tasks…</div>';try{const rows=await api().workflowRpc('workflow_my_tasks',{p_course:course});content.innerHTML=`<section class="page-form-card"><h3>My Tasks</h3><p>Only tasks assigned to you — directly or through Course Team — are listed here.</p>${taskList(rows)}</section>`;$$('[data-task]',content).forEach(b=>b.onclick=()=>void openTaskFromRow(b.dataset.task))}catch(e){content.innerHTML=`<div class="issue error">${esc(e.message)}</div>`}}
async function renderReviewRequests(content){content.innerHTML='<div class="submission-info">Loading review requests…</div>';try{const rows=await api().workflowRpc('workflow_review_requests',{p_course:course});content.innerHTML=`<section class="page-form-card"><h3>Review Requests</h3><p>Admin and authorized course leads can review and approve submissions here.</p>${taskList(rows)}</section>`;$$('[data-task]',content).forEach(b=>b.onclick=()=>void openTaskFromRow(b.dataset.task))}catch(e){content.innerHTML=`<div class="issue error">${esc(e.message)}</div>`}}
function taskList(rows){return `<div class="workflow-table-wrap"><table class="workflow-task-table"><thead><tr><th>#</th><th>Task</th><th>Chapter</th><th>Area</th><th>Status</th><th>Start</th><th>Due</th><th></th></tr></thead><tbody>${(rows||[]).map(r=>{const ch=byId(options.chapters,r.chapter_id);return `<tr><td>${esc(r.stage==='Scientific Draft'?(scientificNumberMap[r.task_key]||r.display_number||'—'):(r.display_number||'—'))}</td><td>${esc(r.title)}</td><td>${esc(ch?`Chapter ${ch.chapter_number} — ${ch.title}`:'—')}</td><td>${esc(r.stage||'—')}</td><td>${statusChip(r.status)}</td><td>${esc(dateText(r.start_date))}</td><td>${esc(dateText(r.due_date))}</td><td><button class="btn small" data-task="${esc(r.task_id)}">Open</button></td></tr>`}).join('')||'<tr><td colspan="8"><div class="empty-state">Nothing here yet.</div></td></tr>'}</tbody></table></div>`}
async function openTaskFromRow(id){const t=tasks.find(x=>x.id===id),w=workflows.find(x=>x.id===t?.workflow_id);if(!t||!w)return;chapter=w.chapter_id;area=areaDefs.find(a=>a.stage===t.stage)?.key||'scientific';mode='chapters';saveState();paint();await taskDetail(id)}
async function renderTeamAssignments(content){content.innerHTML='<div class="submission-info">Loading course team…</div>';try{const rows=await api().workflowRpc('workflow_team_tasks',{p_course:course});const members=new Map();for(const r of roles.filter(x=>x.course_id===course)){if(!members.has(r.user_id))members.set(r.user_id,{id:r.user_id,name:name([...people,...directory],r.user_id,'display_name'),roles:[],count:0});members.get(r.user_id).roles.push(roleLabels[r.role]||r.role)}for(const e of executors){const t=tasks.find(x=>x.id===e.task_id),w=workflows.find(x=>x.id===t?.workflow_id);if(w?.course_id!==course)continue;if(!members.has(e.user_id))members.set(e.user_id,{id:e.user_id,name:name([...people,...directory],e.user_id,'display_name'),roles:['Task Executor'],count:0});members.get(e.user_id).count++}const wids=workflows.filter(w=>w.course_id===course).map(w=>w.id);for(const cr of chapterRoles.filter(x=>wids.includes(x.workflow_id))){if(!members.has(cr.user_id))members.set(cr.user_id,{id:cr.user_id,name:name([...people,...directory],cr.user_id,'display_name'),roles:[],count:0});if(cr.role==='scientific_author'&&!members.get(cr.user_id).roles.includes('Scientific Draft Author'))members.get(cr.user_id).roles.push('Scientific Draft Author')}
 const memberOptions=[...members.values()].sort((a,b)=>a.name.localeCompare(b.name));content.innerHTML=`<section class="team-visibility-note">This section is visible to everyone in the course. Everyone can see who is responsible for each task.</section><section class="page-form-card"><div class="section-head-inline"><div><h3>Team Members</h3><p>Course roles and task responsibility at a glance.</p></div></div><div class="team-member-grid">${memberOptions.map(m=>`<article><div class="avatar-circle">${esc(initials(m.name))}</div><strong>${esc(m.name)}</strong><small>${esc(m.roles.join(' · ')||'Team Member')}</small><span>${m.count} assigned task${m.count===1?'':'s'}</span></article>`).join('')||'<p class="hint">No team members assigned yet.</p>'}</div></section><section class="page-form-card"><div class="section-head-inline team-task-header"><div><h3>Task Assignments</h3><p>Filter the table by executor to see exactly what each person is responsible for.</p></div><label class="team-executor-filter">Executor<select id="teamExecutorFilter"><option value="all">All executors</option><option value="course-team">Course Team</option>${memberOptions.map(m=>`<option value="${esc(m.id)}">${esc(m.name)}</option>`).join('')}</select></label></div><div id="teamTaskTableHost">${teamTaskTable(rows)}</div></section>`;$$('[data-task]',content).forEach(b=>b.onclick=()=>void openTaskFromRow(b.dataset.task));$('#teamExecutorFilter',content).onchange=e=>{const v=e.target.value;$$('[data-team-task-row]',content).forEach(tr=>{const ids=(tr.dataset.executors||'').split(',').filter(Boolean);tr.hidden=v!=='all'&&!ids.includes(v)})}}catch(e){content.innerHTML=`<div class="issue error">${esc(e.message)}</div>`}}
function teamTaskTable(rows){const grouped=new Map();for(const r of rows||[]){if(!grouped.has(r.task_id))grouped.set(r.task_id,{...r,names:[],userIds:[]});if(r.display_name)grouped.get(r.task_id).names.push(r.display_name);if(r.user_id)grouped.get(r.task_id).userIds.push(r.user_id)}for(const t of tasks.filter(t=>workflows.some(w=>w.id===t.workflow_id&&w.course_id===course)&&t.assignment_mode==='course_team')){if(!grouped.has(t.id))grouped.set(t.id,{task_id:t.id,workflow_id:t.workflow_id,chapter_id:workflows.find(w=>w.id===t.workflow_id)?.chapter_id,display_number:t.display_number,title:t.title,stage:t.stage,status:t.status,start_date:t.start_date,due_date:t.due_date,assignment_mode:'course_team',names:[],userIds:['course-team']});else grouped.get(t.id).userIds.push('course-team')}return `<div class="workflow-table-wrap"><table class="workflow-task-table"><thead><tr><th>#</th><th>Task</th><th>Assigned To</th><th>Area</th><th>Due Date</th><th>Status</th><th></th></tr></thead><tbody>${[...grouped.values()].map(r=>`<tr data-team-task-row data-executors="${esc([...new Set(r.userIds||[])].join(','))}"><td>${esc(r.stage==='Scientific Draft'?(scientificNumberMap[r.task_key]||r.display_number||'—'):(r.display_number||'—'))}</td><td>${esc(r.title)}</td><td>${esc(r.assignment_mode==='course_team'?'Course Team':r.names.join(', ')||'Unassigned')}</td><td>${esc(r.stage||'—')}</td><td>${esc(dateText(r.due_date))}</td><td>${statusChip(r.status)}</td><td><button class="btn small" data-task="${esc(r.task_id)}">Open</button></td></tr>`).join('')||'<tr><td colspan="7"><div class="empty-state">No task assignments yet.</div></td></tr>'}</tbody></table></div>`}
window.addEventListener('beforeunload',()=>saveState());
window.TeryaqWorkflow={render,refresh:async()=>{if(host)await render(host)},async openTaskId(id){if(!tasks.length)await load();await openTaskFromRow(id)},async openSubmissionForDocument(doc){const id=doc?.metadata?.workflowTaskId;if(!id)return false;if(!tasks.length)await load();const task=tasks.find(t=>t.id===id),workflow=workflows.find(w=>w.id===task?.workflow_id);if(!task||!workflow)throw new Error('The linked workflow task is unavailable');window.TeryaqSubmissions.setPreferredDocument(doc);await window.TeryaqSubmissions.openForTask(task,workflow);return true;}};
})();
